name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os-name: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    name: Python ${{ matrix.python-version }} (${{ matrix.os-name }})
    runs-on: ${{ matrix.os-name }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Run pre-commit checks
        run: pre-commit install && pre-commit run --all-files
      - name: Run tox
        run: tox -e py
      - name: Upload coverage report
        if: ${{ matrix.os-name == 'ubuntu-latest' && matrix.python-version == '3.9' }}
        uses: codecov/codecov-action@v1
